# Generated by Django 5.2.7 on 2025-10-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermfa',
            name='webauthn_credentials',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='usermfa',
            name='otp_type',
            field=models.CharField(choices=[('NONE', 'None'), ('TOTP', 'Time-based (TOTP)'), ('HOTP', 'Counter-based (HOTP)'), ('WEBAUTHN', 'Biometric / WebAuthn')], default='NONE', max_length=12),
        ),
    ]
