# Generated by Django 5.2.7 on 2025-10-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermfa_webauthn_credentials_alter_usermfa_otp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermfa',
            name='iin',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usermfa',
            name='last_cert_subject',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermfa',
            name='otp_type',
            field=models.CharField(choices=[('NONE', 'None'), ('TOTP', 'Time-based (TOTP)'), ('HOTP', 'Counter-based (HOTP)'), ('WEBAUTHN', 'Biometric / WebAuthn'), ('NCA', 'Digital Signature (NCALayer)')], default='NONE', max_length=12),
        ),
    ]
